### ISSUE TITLE
Error causing site to not load

### ISSUE THREAD

**Issue by adeafblindman** [adeafblindman/Helldivers2map#2]
Control.js:76 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at e.addTo (Control.js:76:11)
    at e.addTo (Control.Layers.js:112:27)
    at mapPoints (map.js:174:22)
    at onMapDataLoad (map.js:616:15)
    at fetchPolygonsSheet (map.js:1034:21)
    at Object.success (map.js:1044:23)
    at c (jquery.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29039)
    at l (jquery.min.js:2:79800)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82254)
﻿

**Comment by adeafblindman** [comment]
Issue was macro saving over data in a different part of the sheet to be over written.
